/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oubowu_exerciseprogram_jni_CheckUtil */

#ifndef _Included_com_oubowu_exerciseprogram_jni_CheckUtil
#define _Included_com_oubowu_exerciseprogram_jni_CheckUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oubowu_exerciseprogram_jni_CheckUtil
 * Method:    getEncodePsw
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL get_encode_psw(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
